# Generated by Django 4.2.11 on 2024-04-05 13:56

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtail_personalisation', '0025_auto_20190822_0627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayrule',
            name='segment',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='wagtail_personalisation.segment'),
        ),
        migrations.AlterField(
            model_name='devicerule',
            name='segment',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='wagtail_personalisation.segment'),
        ),
        migrations.AlterField(
            model_name='origincountryrule',
            name='segment',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='wagtail_personalisation.segment'),
        ),
        migrations.AlterField(
            model_name='queryrule',
            name='segment',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='wagtail_personalisation.segment'),
        ),
        migrations.AlterField(
            model_name='referralrule',
            name='segment',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='wagtail_personalisation.segment'),
        ),
        migrations.AlterField(
            model_name='timerule',
            name='segment',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='wagtail_personalisation.segment'),
        ),
        migrations.AlterField(
            model_name='userisloggedinrule',
            name='segment',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='wagtail_personalisation.segment'),
        ),
        migrations.AlterField(
            model_name='visitcountrule',
            name='segment',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)ss', to='wagtail_personalisation.segment'),
        ),
    ]
